Resources:
  myfunctionServiceRole41691664:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/my-function/ServiceRole/Resource
  myfunctionDF753486:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295aS3Bucket88A629F5
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295aS3VersionKey408ECF15
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295aS3VersionKey408ECF15
      Role:
        Fn::GetAtt:
          - myfunctionServiceRole41691664
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.main
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 5
    DependsOn:
      - myfunctionServiceRole41691664
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/my-function/Resource
      aws:asset:path: /home/admin/workspace/prototype-email-subscription/cdk.out/asset.01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295a
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Resource
  EndpointCloudWatchRoleC3C64E0F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/CloudWatchRole/Resource
  EndpointAccountB8304247:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EndpointCloudWatchRoleC3C64E0F
          - Arn
    DependsOn:
      - EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Account
  EndpointDeployment318525DA27d2b80b5e52a582125567360490c85b:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      DeploymentId:
        Ref: EndpointDeployment318525DA27d2b80b5e52a582125567360490c85b
      StageName: prod
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/DeploymentStage.prod/Resource
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionEmailSubscriptionStackEndpoint4A7A74C0ANYproxy7108201E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - myfunctionDF753486
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/*
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.EmailSubscriptionStackEndpoint4A7A74C0.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestEmailSubscriptionStackEndpoint4A7A74C0ANYproxy7BE4B788:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - myfunctionDF753486
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.EmailSubscriptionStackEndpoint4A7A74C0.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - myfunctionDF753486
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionEmailSubscriptionStackEndpoint4A7A74C0ANY6171C85F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - myfunctionDF753486
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/ANY/ApiPermission.EmailSubscriptionStackEndpoint4A7A74C0.ANY..
  EndpointANYApiPermissionTestEmailSubscriptionStackEndpoint4A7A74C0ANY2A8D0D8F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - myfunctionDF753486
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/ANY/ApiPermission.Test.EmailSubscriptionStackEndpoint4A7A74C0.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - myfunctionDF753486
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAA21QXU/DMAz8LbynWSuQ4JEyxBMfU/kFIfW2dE1SxQ6jivLfSVI2hsSTz9bZd+eGh6aueX11L45Yyf6wCtI64OGdhDywFhEowZ0yO9YBWu8ksLU1SM5LYuut2QgnNBC43PxStiaxekXKmsjy7TAK/dGLytgeBuSvpTx5IzOFKaF56OxYNnONDK8rkeWRFxds2echEc5rWR+cVohZJ0bW1Hd/whRlMamdIDiKmYfnciX5pHZSP5ZPsJXSekPsEabRzhpMCXjR5U8Uhws4pX0QCGzj7Nd8mf+MX4D2ts+jBcV/0kZW3p7aN0+TpzTIj+IDrj6bG97cplQDKlW5ZFBp4N1SvwFtGYZqwAEAAA==
    Metadata:
      aws:cdk:path: EmailSubscriptionStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295aS3Bucket88A629F5:
    Type: String
    Description: S3 bucket for asset "01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295a"
  AssetParameters01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295aS3VersionKey408ECF15:
    Type: String
    Description: S3 key for asset version "01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295a"
  AssetParameters01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295aArtifactHash51F28FA3:
    Type: String
    Description: Artifact hash for asset "01664783f1610325d5defed011d077ab78f8cefd91d338282f0150e3ad7c295a"
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

